apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP
  template:
    metadata:
      labels:
        app: $APP
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - image: sonatype/nexus3
          imagePullPolicy: Always
          name: $APP
          ports:
            - containerPort: $PORT
          volumeMounts:
            - mountPath: /nexus-data
              name: k8-dev-nexus
      volumes:
        - name: k8-dev-nexus
          azureDisk:
            kind: Managed
            diskName: k8-dev-nexus
            diskURI: /subscriptions/15898331-6d5a-4032-8490-c1608fea8f47/resourceGroups/dev/providers/Microsoft.Compute/disks/k8-dev-nexus
